production: &build
  adapter: postgresql
  encoding: unicode
  database: yeti_build
  pool: 5
  username: postgres
  password:
  host: 127.0.0.1
  schema_search_path: >
    gui, public, switch,
    billing, class4, runtime_stats,
    sys, logs, data_import
  port: 5432
  #min_messages: warning

test:
  <<: *build
  database: yeti_test

secondbase:
  production: &build_cdr
    adapter: postgresql
    encoding: unicode
    database: yeti_cdr_build
    pool: 5
    username: postgres
    password:
    host: 127.0.0.1
    schema_search_path: 'cdr, reports, billing'
    port: 5432
    #min_messages: warning

  test:
    <<: *build_cdr
    database: yeti_cdr_test

