production:
  primary: &build
    adapter: postgresql
    encoding: unicode
    # PGQ_PROCESSORS_TEST is set to true for pgq-processors tests to create separate db
    # to not interfere with main test suite when running make tasks in parallel e.g. make -j 4
    database: yeti_build<%= '-pgq-processors' if ENV['PGQ_PROCESSORS_TEST'] %><%= ENV['TEST_ENV_NUMBER'] %>
    pool: 5
    username: postgres
    password:
    host: <%= (ENV['YETI_DB_HOST'] || 'localhost') %>
    schema_search_path: >
      gui, public, switch,
      billing, class4, runtime_stats,
      sys, logs, data_import
    port: <%= (ENV['YETI_DB_PORT'] || '5432' ) %>
    #min_messages: warning
    schema_cache_path: tmp/primary_schema_cache.yml
  cdr: &build_cdr
    adapter: postgresql
    encoding: unicode
    # PGQ_PROCESSORS_TEST is set to true for pgq-processors tests to create separate db
    # to not interfere with main test suite when running make tasks in parallel e.g. make -j 4
    database: yeti_cdr_build<%= '-pgq-processors' if ENV['PGQ_PROCESSORS_TEST'] %><%= ENV['TEST_ENV_NUMBER'] %>
    pool: 5
    username: postgres
    password:
    host: <%= (ENV['CDR_DB_HOST'] || 'localhost') %>
    schema_search_path: 'cdr, reports, billing, public'
    port: <%= (ENV['CDR_DB_PORT'] || '5432') %>
    migrations_paths: db/cdr_migrate
    #min_messages: warning
    schema_cache_path: tmp/cdr_schema_cache.yml

test:
  primary:
    <<: *build
    database: yeti_test<%= ENV['TEST_ENV_NUMBER'] %>
  cdr:
    <<: *build_cdr
    database: yeti_cdr_test<%= ENV['TEST_ENV_NUMBER'] %>
    migrations_paths: db/cdr_migrate
