# frozen_string_literal: true

source 'https://rubygems.org'

# Use ActiveAdmin 4.x beta
gem 'activeadmin', '4.0.0.beta16'

gemspec name: 'activeadmin_tom_select'

gem 'devise', '~> 4.9', group: :test

gem 'propshaft', '~> 1.2', group: :test

gem 'rails', '~> 8.0', group: :test
