#!/usr/bin/env ruby
# frozen_string_literal: true

log_path = ARGV[0]
filter_qty = (ARGV[1] || 10).to_i

unless File.exist?(log_path)
  puts "File #{log_path.inspect} does not exist. skipping"
  exit
end

content = File.read(log_path).split("\n").select { |line| line.start_with?('spec/') }
data = content.map { |line| line.split(':') }.sort_by { |parts| parts[1].to_f }.reverse[0..filter_qty]
output_content = data.map { |parts| "  #{parts[1].to_f.round(2)}\tseconds for #{parts[0]}" }

puts "Top #{filter_qty} slowest spec files:"
puts output_content.join("\n")
puts "\nTotal #{content.size} spec files."
