# frozen_string_literal: true

source 'http://rubygems.org'

gem 'activemodel', '~> 6.1.7.1'
gem 'activeresource'
gem 'activeresource-persistent', require: 'active_resource/persistent'
gem 'bundler'
gem 'bunny'
gem 'http_logger'
gem 'net-smtp'
gem 'pg'
gem 'pgq', path: 'ext/pgq'
gem 'pony'
gem 'rake'
gem 'rest-client'
gem 'syslog-logger'

group :test, :development do
  gem 'bunny-mock'
  gem 'byebug'
  gem 'rspec'
  gem 'webmock'
end
