source "http://rubygems.org"

gem 'rake'
gem 'bundler'
gem 'pgq', path: 'ext/pgq'
gem 'pg'
gem 'activeresource'
gem 'activeresource-persistent', require: 'active_resource/persistent'
gem 'http_logger'
gem 'syslog-logger'
gem 'pony'
gem 'rest-client'
