# frozen_string_literal: true

namespace :pgq do
  desc 'Start PQG worker'
  task :worker do
    require_relative 'pgq_env'

    pgq_env = PgqEnv.new

    w = Pgq::Worker.new(pgq_env)

    pid_file = ENV['pid_file']

    if pid_file.present?
      raise 'pid file exists!' if File.exist? pid_file

      File.open(pid_file, 'w') { |f| f.puts Process.pid }
    end

    begin
      w.run
    ensure
      File.delete pid_file if pid_file.present?
    end
  end
end
