# frozen_string_literal: true

namespace :pgq do
  desc 'Start PQG worker'
  task :worker do
    require_relative 'pgq_env'

    pgq_env = PgqEnv.new

    w = Pgq::Worker.new(pgq_env)

    pid_file = ENV['pid_file']
    raise 'pid_file is mandatory option!' if pid_file.blank?
    raise 'pid file exists!' if File.exist? pid_file

    File.open(pid_file, 'w') { |f| f.puts Process.pid }
    begin
      w.run
    ensure
      File.delete pid_file
    end
  end
end
