# frozen_string_literal: true

RSpec.describe 'Update Gateway', type: :feature, js: true do
  include_context :login_as_admin

  before do
    visit edit_gateway_path(gateway.id)
  end

  context 'validate autogenerated credentials' do
    before do
      click_on 'Signaling'
    end

    context 'when credentials is empty' do
      let!(:gateway) { FactoryBot.create(:gateway, incoming_auth_username: nil, incoming_auth_password: nil) }

      it 'should not autogenerate credential for :incoming_auth_username' do
        incoming_auth_username = find_field('gateway_incoming_auth_username')
        expect(incoming_auth_username).to be_present
        expect(incoming_auth_username.value).to be_empty
      end

      it 'should not autogenerate credential for :incoming_auth_password' do
        incoming_auth_password = find_field('gateway_incoming_auth_password')
        expect(incoming_auth_password).to be_present
        expect(incoming_auth_password.value).to be_empty
      end
    end

    context 'when credentials are present' do
      let!(:gateway) { FactoryBot.create(:gateway, incoming_auth_username: 'TestCredential', incoming_auth_password: 'TestCredential') }

      it 'should not replace already existing value for :incoming_auth_username' do
        incoming_auth_username = find_field('gateway_incoming_auth_username')
        expect(incoming_auth_username).to be_present
        expect(incoming_auth_username.value).to be_present
        expect(incoming_auth_username.value).to eq('TestCredential')
      end

      it 'should not replace already existing value for :incoming_auth_password' do
        incoming_auth_password = find_field('gateway_incoming_auth_password')
        expect(incoming_auth_password).to be_present
        expect(incoming_auth_password.value).to be_present
        expect(incoming_auth_password.value).to eq('TestCredential')
      end
    end
  end
end
