# frozen_string_literal: true

RSpec.describe 'Create new Gateway', type: :feature, js: true do
  subject do
    visit new_gateway_path

    fill_form!
    submit_form!
  end

  include_context :login_as_admin

  include_context :incoming_registrations_stub_helpers do
    let(:stub_incoming_registrations_collection_query) do
      { auth_id: a_kind_of(Integer), empty_on_error: false }
    end
    before do
      FactoryBot.create(:node)
      stub_incoming_registrations_collection
    end
  end

  let!(:contractor) { FactoryBot.create(:customer) }
  let!(:codec_group) { FactoryBot.create(:codec_group) }
  let!(:termination_src_numberlist) { FactoryBot.create(:numberlist) }
  let!(:termination_dst_numberlist) { FactoryBot.create(:numberlist) }
  let!(:customer) { FactoryBot.create(:customer) }
  let!(:vendor) { FactoryBot.create(:vendor) }
  let!(:codec_group) { FactoryBot.create(:codec_group) }

  let(:fill_form!) do
    fill_in 'Name', with: 'gw123'
    fill_in_tom_select 'Contractor', with: contractor.display_name, ajax: true
    switch_tab 'Media'
    fill_in_tom_select 'Codec group', with: codec_group.display_name
    switch_tab 'Translations'
    fill_in_tom_select 'Termination SRC Numberlist', with: termination_src_numberlist.display_name, ajax: true
    fill_in_tom_select 'Termination DST Numberlist', with: termination_dst_numberlist.display_name, ajax: true
  end
  let(:submit_form!) do
    click_submit('Create Gateway')
  end

  context 'with termination' do
    let(:fill_form!) do
      super()
      switch_tab 'Signaling'
      fill_in 'Host', with: '192.168.112.12'
    end

    it 'creates record' do
      subject
      record = Gateway.last
      expect(record).to be_present
      expect(record).to have_attributes(
        contractor_id: contractor.id,
        name: 'gw123',
        host: '192.168.112.12',
        allow_termination: true,
        codec_group_id: codec_group.id,
        termination_src_numberlist:,
        termination_dst_numberlist:
      )
    end

    include_examples :changes_records_qty_of, Gateway, by: 1
    include_examples :shows_flash_message, :notice, 'Gateway was successfully created.'
  end

  context 'without termination' do
    let(:fill_form!) do
      super()
      switch_tab 'General'
      uncheck 'Allow termination'
    end

    it 'creates record' do
      subject
      record = Gateway.last
      expect(record).to be_present
      expect(record).to have_attributes(
        contractor_id: contractor.id,
        name: 'gw123',
        host: '',
        allow_termination: false,
        codec_group_id: codec_group.id,
        termination_src_numberlist:,
        termination_dst_numberlist:
      )
    end

    include_examples :changes_records_qty_of, Gateway, by: 1
    include_examples :shows_flash_message, :notice, 'Gateway was successfully created.'
  end

  context 'validate autogenerated credentials' do
    let(:stub_incoming_registrations_collection) { nil }

    let(:fill_form!) do
      super()
      switch_tab 'Signaling'
    end
    let(:submit_form!) { nil }

    context 'when credentials is empty' do
      it 'should generate new credential by click on the link in hint for :incoming_auth_username with 20 chars' do
        subject

        click_link('Сlick to fill random username')
        incoming_auth_username = find_field('gateway_incoming_auth_username')
        expect(incoming_auth_username).to be_present
        expect(incoming_auth_username.value).to be_present
        expect(incoming_auth_username.value).to match(/\A[a-zA-Z0-9]+\z/)
        expect(incoming_auth_username.value.length).to eq(20)
      end

      it 'should generate new credential by click on the link in hint for :incoming_auth_password with 20 chars' do
        subject

        click_link('Сlick to fill random password')
        incoming_auth_password = find_field('gateway_incoming_auth_password')
        expect(incoming_auth_password).to be_present
        expect(incoming_auth_password.value).to be_present
        expect(incoming_auth_password.value).to match(/\A[a-zA-Z0-9]+\z/)
        expect(incoming_auth_password.value.length).to eq(20)
      end

      it 'should not autogenerate new credential for :incoming_auth_username' do
        subject

        incoming_auth_username = find_field('gateway_incoming_auth_username')
        expect(incoming_auth_username).to be_present
        expect(incoming_auth_username.value).to be_empty
      end

      it 'should not autogenerate new credential for :incoming_auth_password' do
        subject

        incoming_auth_password = find_field('gateway_incoming_auth_password')
        expect(incoming_auth_password).to be_present
        expect(incoming_auth_password.value).to be_empty
      end
    end

    context 'when credentials are present' do
      let(:fill_form!) do
        super()

        fill_in 'Host', with: '192.168.112.12'
        fill_in 'gateway_incoming_auth_username', with: 'TestCredential'
        fill_in 'gateway_incoming_auth_password', with: 'TestCredential'
      end

      it 'should generate new credential by click on the link in hint for :incoming_auth_username with 20 chars' do
        subject

        click_link('Сlick to fill random username')
        incoming_auth_username = find_field('gateway_incoming_auth_username')
        expect(incoming_auth_username).to be_present
        expect(incoming_auth_username.value).to be_present
        expect(incoming_auth_username.value).to match(/\A[a-zA-Z0-9]+\z/)
        expect(incoming_auth_username.value.length).to eq(20)
        expect(incoming_auth_username.value).not_to eq('TestCredential')
      end

      it 'should generate new credential by click on the link in hint for :incoming_auth_password with 20 chars' do
        subject

        click_link('Сlick to fill random password')
        incoming_auth_password = find_field('gateway_incoming_auth_password')
        expect(incoming_auth_password).to be_present
        expect(incoming_auth_password.value).to be_present
        expect(incoming_auth_password.value).to match(/\A[a-zA-Z0-9]+\z/)
        expect(incoming_auth_password.value.length).to eq(20)
        expect(incoming_auth_password.value).not_to eq('TestCredential')
      end

      it 'should not autogenerate new credential for :incoming_auth_username' do
        subject

        incoming_auth_username = find_field('gateway_incoming_auth_username')
        expect(incoming_auth_username).to be_present
        expect(incoming_auth_username.value).to be_present
        expect(incoming_auth_username.value).to eq('TestCredential')
      end

      it 'should not autogenerate new credential for :incoming_auth_password' do
        subject

        incoming_auth_password = find_field('gateway_incoming_auth_password')
        expect(incoming_auth_password).to be_present
        expect(incoming_auth_password.value).to be_present
        expect(incoming_auth_password.value).to eq('TestCredential')
      end
    end
  end

  context 'with auth credentials' do
    let(:fill_form!) do
      super()

      switch_tab 'Signaling'
      fill_in 'Host', with: '192.168.112.12'
      fill_in 'gateway_incoming_auth_username', with: 'TestCredentialUsername'
      fill_in 'gateway_incoming_auth_password', with: 'TestCredentialPassword'
    end

    it 'should create gateway with credentials' do
      expect do
        subject

        expect(page).to have_flash_message('Gateway was successfully created.', type: :notice)
      end.to change { Gateway.count }.by(1)

      gateway = Gateway.last
      expect(gateway).to have_attributes(
                           incoming_auth_password: 'TestCredentialPassword',
                           incoming_auth_username: 'TestCredentialUsername'
                         )
    end
  end
end
